services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    env_file:
      - .env
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./volumes/ollama:/root/.ollama

  open-webui:
      image: ghcr.io/open-webui/open-webui:main
      container_name: open-webui
      env_file:
        - .env
      ports:
        - "3000:8080"
      volumes:
        - ./volumes/open-webui:/app/backend/data
      depends_on:
        - ollama

